### ISSUE TITLE
Setup Bash Script is broken for Debian

### ISSUE THREAD

**Issue by devGregA** [rackerlabs/django-DefectDojo#22] opened 2015-03-26 04:48 UTC
Installed /usr/local/lib/python2.7/dist-packages/python_nmap-0.3.4-py2.7.egg
Searching for gunicorn==19.1.1
Reading https://pypi.python.org/simple/gunicorn/
Best match: gunicorn 19.1.1
Downloading https://pypi.python.org/packages/source/g/gunicorn/gunicorn-19.1.1.tar.gz#md5=eaa72bff5341c05169b76ce3dcbb8140
Processing gunicorn-19.1.1.tar.gz
Writing /tmp/easy_install-BzslcD/gunicorn-19.1.1/setup.cfg
Running gunicorn-19.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-BzslcD/gunicorn-19.1.1/egg-dist-tmp-6CGA3_
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyo' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'examples'
warning: no previously-included files matching '*.pyo' found under directory 'examples'
  File "build/bdist.linux-x86_64/egg/gunicorn/workers/_gaiohttp.py", line 64
    yield from self.wsgi.close()
             ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.1.1-py2.7.egg/gunicorn/workers/_gaiohttp.py", line 64
    yield from self.wsgi.close()
             ^
SyntaxError: invalid syntax

Adding gunicorn 19.1.1 to easy-install.pth file
Installing gunicorn_paster script to /usr/local/bin
Installing gunicorn script to /usr/local/bin
Installing gunicorn_django script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/gunicorn-19.1.1-py2.7.egg
Searching for django-tastypie-swagger
Best match: django-tastypie-swagger [unknown version]
Downloading https://github.com/concentricsky/django-tastypie-swagger/tarball/v0.1.3#egg=django-tastypie-swagger
Processing v0.1.3
Writing /tmp/easy_install-hJQiiA/concentricsky-django-tastypie-swagger-a8ba1c2/setup.cfg
Running concentricsky-django-tastypie-swagger-a8ba1c2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-hJQiiA/concentricsky-django-tastypie-swagger-a8ba1c2/egg-dist-tmp-K_OQS5
warning: no files found matching 'LICENSE'
warning: no files found matching 'README.rst'
warning: no files found matching '3RDPARTYLICENSES'
Adding django-tastypie-swagger 0.1.3 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg
Searching for django-tastypie==0.12.1
Reading https://pypi.python.org/simple/django-tastypie/
Best match: django-tastypie 0.12.1
Downloading https://pypi.python.org/packages/source/d/django-tastypie/django-tastypie-0.12.1.tar.gz#md5=fbe635644c3551fbe66dd50e7e115537
Processing django-tastypie-0.12.1.tar.gz
Writing /tmp/easy_install-TSn4HV/django-tastypie-0.12.1/setup.cfg
Running django-tastypie-0.12.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-TSn4HV/django-tastypie-0.12.1/egg-dist-tmp-XahtKC
warning: no files found matching 'VERSION'
Adding django-tastypie 0.12.1 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/django_tastypie-0.12.1-py2.7.egg
Searching for django-secure==1.0
Reading https://pypi.python.org/simple/django-secure/
Best match: django-secure 1.0
Downloading https://pypi.python.org/packages/source/d/django-secure/django-secure-1.0.tar.gz#md5=68fcc9570371e1e9f5ee57958a86a138
Processing django-secure-1.0.tar.gz
Writing /tmp/easy_install-oH0WK4/django-secure-1.0/setup.cfg
Running django-secure-1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-oH0WK4/django-secure-1.0/egg-dist-tmp-ESoMsa
Adding django-secure 1.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/django_secure-1.0-py2.7.egg
Searching for Pillow==2.3.0
Reading https://pypi.python.org/simple/Pillow/
Best match: Pillow 2.3.0
Downloading https://pypi.python.org/packages/source/P/Pillow/Pillow-2.3.0.zip#md5=56b6614499aacb7d6b5983c4914daea7
Processing Pillow-2.3.0.zip
Writing /tmp/easy_install-jQA1cd/Pillow-2.3.0/setup.cfg
Running Pillow-2.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jQA1cd/Pillow-2.3.0/egg-dist-tmp-O0uE2H
libImaging/Unpack.c:867:1: warning: ‘copy3’ defined but not used [-Wunused-function]
 copy3(UINT8* out, const UINT8* in, int pixels)
 ^
--------------------------------------------------------------------
PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 2.3.0
platform     linux2 2.7.6 (default, Mar 22 2014, 22:59:56)
             [GCC 4.8.2]
--------------------------------------------------------------------
*** TKINTER support not available
*** JPEG support not available
--- ZLIB (PNG/ZIP) support available
*** LIBTIFF support not available
*** FREETYPE2 support not available
*** LITTLECMS2 support not available
*** WEBP support not available
*** WEBPMUX support not available
--------------------------------------------------------------------
To add a missing option, make sure you have the required
library, and set the corresponding ROOT variable in the
setup.py script.

To check the build, run the selftest.py script.

Adding Pillow 2.3.0 to easy-install.pth file
Installing pildriver.py script to /usr/local/bin
Installing pilconvert.py script to /usr/local/bin
Installing pilfont.py script to /usr/local/bin
Installing pilfile.py script to /usr/local/bin
Installing pilprint.py script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/Pillow-2.3.0-py2.7-linux-x86_64.egg
Searching for MySQL-python==1.2.5
Reading https://pypi.python.org/simple/MySQL-python/
Best match: MySQL-python 1.2.5
Downloading https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.5.zip#md5=654f75b302db6ed8dc5a898c625e030c
Processing MySQL-python-1.2.5.zip
Writing /tmp/easy_install-uXRkHw/MySQL-python-1.2.5/setup.cfg
Running MySQL-python-1.2.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-uXRkHw/MySQL-python-1.2.5/egg-dist-tmp-Owj4RP
In file included from _mysql.c:44:0:
/usr/include/mysql/my_config.h:422:0: warning: "HAVE_WCSCOLL" redefined [enabled by default]
 #define HAVE_WCSCOLL
 ^
In file included from /usr/include/python2.7/pyconfig.h:3:0,
                 from /usr/include/python2.7/Python.h:8,
                 from _mysql.c:29:
/usr/include/x86_64-linux-gnu/python2.7/pyconfig.h:911:0: note: this is the location of the previous definition
 #define HAVE_WCSCOLL 1
 ^
zip_safe flag not set; analyzing archive contents...
Adding MySQL-python 1.2.5 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/MySQL_python-1.2.5-py2.7-linux-x86_64.egg
Searching for Django>=1.7
Reading https://pypi.python.org/simple/Django/
Best match: Django 1.7.7
Downloading https://pypi.python.org/packages/source/D/Django/Django-1.7.7.tar.gz#md5=a62d6598966947d150525ad2ab20fb0c
Processing Django-1.7.7.tar.gz
Writing /tmp/easy_install-6frCdK/Django-1.7.7/setup.cfg
Running Django-1.7.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6frCdK/Django-1.7.7/egg-dist-tmp-1yh8Jx
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
Adding Django 1.7.7 to easy-install.pth file
Installing django-admin.py script to /usr/local/bin
Installing django-admin script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg
Searching for meld3>=0.6.5
Reading https://pypi.python.org/simple/meld3/
Best match: meld3 1.0.0
Downloading https://pypi.python.org/packages/source/m/meld3/meld3-1.0.0.tar.gz#md5=ca270506dd4ecb20ae26fa72fbd9b0be
Processing meld3-1.0.0.tar.gz
Writing /tmp/easy_install-0CwtYB/meld3-1.0.0/setup.cfg
Running meld3-1.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0CwtYB/meld3-1.0.0/egg-dist-tmp-SBJDW5
zip_safe flag not set; analyzing archive contents...
Adding meld3 1.0.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/meld3-1.0.0-py2.7.egg
Searching for python-dateutil>=1.5,!=2.0
Reading https://pypi.python.org/simple/python-dateutil/
Reading http://labix.org/python-dateutil
Reading https://dateutil.readthedocs.org
Best match: python-dateutil 2.4.1
Downloading https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.4.1.zip#md5=e3f4c3bf3072e1de7a008f44b0ebddad
Processing python-dateutil-2.4.1.zip
Writing /tmp/easy_install-QSx0BL/python-dateutil-2.4.1/setup.cfg
Running python-dateutil-2.4.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-QSx0BL/python-dateutil-2.4.1/egg-dist-tmp-bojcHn
Adding python-dateutil 2.4.1 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/python_dateutil-2.4.1-py2.7.egg
Searching for python-mimeparse>=0.1.4
Reading https://pypi.python.org/simple/python-mimeparse/
Best match: python-mimeparse 0.1.4
Downloading https://pypi.python.org/packages/source/p/python-mimeparse/python-mimeparse-0.1.4.tar.gz#md5=1d2816a16f17dcfe0c613da611fe7e13
Processing python-mimeparse-0.1.4.tar.gz
Writing /tmp/easy_install-inGrxW/python-mimeparse-0.1.4/setup.cfg
Running python-mimeparse-0.1.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-inGrxW/python-mimeparse-0.1.4/egg-dist-tmp-fdZ0zE
zip_safe flag not set; analyzing archive contents...
Adding python-mimeparse 0.1.4 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/python_mimeparse-0.1.4-py2.7.egg
Searching for wsgiref==0.1.2
Best match: wsgiref 0.1.2
Adding wsgiref 0.1.2 to easy-install.pth file

Using /usr/lib/python2.7
Searching for requests==2.2.1
Best match: requests 2.2.1
Adding requests 2.2.1 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for six==1.5.2
Best match: six 1.5.2
six 1.5.2 is already the active version in easy-install.pth

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for DefectDojo==1.0
System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
	HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.
Migrations for 'dojo':
  0001_initial.py:
    - Create model BurpRawIssue
    - Create model BurpRawIssueDetailItems
    - Create model BurpRawIssues
    - Create model BurpRawRequestResponse
    - Create model Check_List
    - Create model Contact
    - Create model CWE
    - Create model Development_Environment
    - Create model Endpoint
    - Create model Engagement
    - Create model Engagement_Type
    - Create model Finding
    - Create model IPScan
    - Create model Notes
    - Create model Product
    - Create model Product_Line
    - Create model Product_Type
    - Create model Report_Type
    - Create model Risk_Acceptance
    - Create model Scan
    - Create model ScanSettings
    - Create model Test
    - Create model Test_Type
    - Create model ThreatModel
    - Create model VA
    - Add field test_type to test
    - Add field scan_settings to scan
    - Add field prod_type to product
    - Add field scan to ipscan
    - Add field notes to finding
    - Add field reporter to finding
    - Add field test to finding
    - Add field eng_type to engagement
    - Add field lead to engagement
    - Add field product to engagement
    - Add field report_type to engagement
    - Add field requester to engagement
    - Add field risk_acceptance to engagement
    - Add field auth_issues to check_list
    - Add field author_issues to check_list
    - Add field config_issues to check_list
    - Add field crypto_issues to check_list
    - Add field data_issues to check_list
    - Add field engagement to check_list
    - Add field other_issues to check_list
    - Add field sensitive_issues to check_list
    - Add field session_issues to check_list
    - Add field burpIssues to burprawissue
    - Create proxy model Dojo_User
System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
	HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.
Operations to perform:
  Synchronize unmigrated apps: djangobower
  Apply all migrations: dojo, sessions, admin, sites, auth, tastypie, contenttypes
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying dojo.0001_initial.../usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/db/models/fields/__init__.py:1282: RuntimeWarning: DateTimeField Notes.date received a naive datetime (2015-03-25 23:43:09.497235) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/db/models/fields/__init__.py:1282: RuntimeWarning: DateTimeField Risk_Acceptance.created received a naive datetime (2015-03-25 23:43:12.781729) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/db/models/fields/__init__.py:1282: RuntimeWarning: DateTimeField Scan.date received a naive datetime (2015-03-25 23:43:12.841282) while time zone support is active.
  RuntimeWarning)

/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/db/models/fields/__init__.py:1282: RuntimeWarning: DateTimeField ScanSettings.date received a naive datetime (2015-03-25 23:43:12.892175) while time zone support is active.
  RuntimeWarning)

 OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying tastypie.0001_initial... OK
System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
	HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.
System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
	HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.
Operations to perform:
  Synchronize unmigrated apps: djangobower
  Apply all migrations: dojo, sessions, admin, sites, auth, tastypie, contenttypes
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  No migrations to apply.

You have installed Django's auth system, and don't have any superusers defined.
Would you like to create one now? (yes/no): yes
System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
	HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.
Username (leave blank to use 'root'): 
Email address: 
Password: 
Password (again): 
Superuser created successfully.
Unknown command: 'bower'
Type 'manage.py help' for usage.

You have requested to collect static files at the destination
location as specified in your settings:

    /var/www/example.com/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Copying '/root/django-DefectDojo/dojo/static/dojo/js/index.js'
Copying '/root/django-DefectDojo/dojo/static/dojo/css/dojo.css'
Copying '/root/django-DefectDojo/dojo/static/dojo/img/chop.png'
Copying '/root/django-DefectDojo/dojo/static/dojo/img/index.jpg'
Copying '/root/django-DefectDojo/dojo/static/dojo/img/cloud_sec.png'
Copying '/root/django-DefectDojo/dojo/static/dojo/img/glyphicons-halflings-white.png'
Copying '/root/django-DefectDojo/dojo/static/dojo/img/favicon.ico'
Copying '/root/django-DefectDojo/dojo/static/dojo/img/glyphicons-halflings.png'
Copying '/root/django-DefectDojo/dojo/static/dojo/img/logo.png'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/SelectFilter2.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/LICENSE-JQUERY.txt'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/calendar.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/collapse.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/prepopulate.min.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/actions.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/timeparse.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/SelectBox.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/prepopulate.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/jquery.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/actions.min.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/urlify.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/inlines.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/jquery.init.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/inlines.min.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/jquery.min.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/core.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/collapse.min.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/js/admin/DateTimeShortcuts.js'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/css/base.css'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/css/changelists.css'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/css/rtl.css'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/css/login.css'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/css/forms.css'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/css/dashboard.css'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/css/widgets.css'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/css/ie.css'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/inline-delete.png'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/icon_deletelink.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/icon-unknown.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/selector-search.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/nav-bg-selected.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/tooltag-add.png'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/icon-no.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/selector-icons.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/deleted-overlay.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/icon_success.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/default-bg.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/inline-splitter-bg.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/icon_error.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/inline-delete-8bit.png'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/nav-bg-reverse.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/changelist-bg.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/icon_clock.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/nav-bg-grabber.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/icon_calendar.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/icon_searchbox.png'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/icon_changelink.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/default-bg-reverse.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/sorting-icons.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/icon_addlink.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/icon-yes.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/nav-bg.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/inline-restore.png'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/inline-restore-8bit.png'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/icon_alert.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/changelist-bg_rtl.gif'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/tooltag-arrowright.png'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/gis/move_vertex_on.png'
Copying '/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/admin/static/admin/img/gis/move_vertex_off.png'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/js/swagger-ui.js'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/js/swagger-ui.min.js'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/js/lib/jquery.wiggle.min.js'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/js/lib/swagger.js'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/js/lib/jquery-1.8.0.min.js'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/js/lib/underscore-min.js'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/js/lib/highlight.7.3.pack.js'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/js/lib/backbone-min.js'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/js/lib/jquery.slideto.min.js'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/js/lib/jquery.ba-bbq.min.js'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/js/lib/handlebars-1.0.rc.1.js'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/images/wordnik_api.png'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/images/pet_store_api.png'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/images/logo_small.png'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/images/throbber.gif'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/css/screen.css'
Copying '/usr/local/lib/python2.7/dist-packages/django_tastypie_swagger-0.1.3-py2.7.egg/tastypie_swagger/static/tastypie_swagger/css/hightlight.default.css'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle_noargs
    collected = self.collect()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/staticfiles/management/commands/collectstatic.py", line 98, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/staticfiles/finders.py", line 111, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/contrib/staticfiles/utils.py", line 27, in get_files
    directories, files = storage.listdir(location)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.7.7-py2.7.egg/django/core/files/storage.py", line 270, in listdir
    for entry in os.listdir(path):
OSError: [Errno 2] No such file or directory: '/root/django-DefectDojo/dojo/components/components'
==============================================================================

SUCCESS! Now edit your settings.py file in the 'dojo' directory to complete the installation.

**Comment by grendel513** [comment] 2015-03-26 05:00
When the Pillow install failed, it stops processing the rest of the requirements, that is why Unknown command: 'bower' is present.  It never installed django-bower, which is listed in setup.py's install requirements.  We should remove Pillow - I have no idea why it is there.

Can you try removing it on your local box and rerun the setup script?

**Comment by grendel513** [comment] 2015-03-26 06:27
I think the problem is "Django 1.7 requires Python 2.7 or above" see https://docs.djangoproject.com/fr/1.7/releases/1.7/ for details.  We should recommend a virtualenv?

**Comment by devGregA** [comment] 2015-03-26 14:48
2.7 is standard for both deb & rhel. I'l try removing pillow

**Comment by devGregA** [comment] 2015-03-26 14:50
Removed pillow still hit the same error.

**Comment by grendel513** [comment] 2015-03-27 02:25
fixed by https://github.com/rackerlabs/django-DefectDojo/pull/23

**Closed by grendel513** 2015-03-27 02:25 UTC
Labels: bug
